image: rust:1.31.1

build:
  stage: build
  script:
  - cargo build
  - cargo build --release
  artifacts: 
    paths:
    - target/
  cache:
    paths:
    - target/

test:
  stage: test
  dependencies:
  - build
  script:
  - cargo test
  cache: 
    paths: 
    - target/
