image: rust:1.31.1

build:
  stage: build
  script:
  - cargo build
  - cargo build --release
  artifacts: 
    paths:
    - target/
  cache:
    paths:
    - target/

test:
  stage: test
  image: xd009642/tarpaulin
  dependencies:
  - build
  script:
  - cargo tarpaulin -v
  coverage: '/^\s*(\d+\s*%)\s*coverage/'
  cache: 
    paths: 
    - target/
